import MarketingNav from "@/components/MarketingNav";
import { ArrowRight, CheckCircle2, CircleDot, MapPinned, ShieldCheck, TowerControl } from "lucide-react";
import { Link } from "wouter";

const phases = [{ title: "Definir o recorte", body: "Selecionar uma região, conjunto de sites ou família de obrigações que represente uma dor relevante e seja viável de validar." }, { title: "Importar e normalizar", body: "Organizar licenças, planilhas, documentos e responsáveis existentes em uma estrutura única, sem exigir uma base perfeita no primeiro dia." }, { title: "Conectar decisões", body: "Vincular condicionantes, evidências, planos de ação quando necessários, responsáveis e aprovações à rotina da equipe ambiental." }, { title: "Medir o resultado", body: "Revisar cobertura documental, pendências críticas, prazos próximos e o tempo poupado antes de decidir a expansão." }];

export default function PilotTelecom() {
  return <div className="marketing-page"><MarketingNav /><main><section className="pilot-hero"><div><p className="eyebrow">Piloto Regularizando para telecom</p><h1>Valide a gestão ambiental de sites distribuídos <em>antes de escalar.</em></h1><p>O piloto transforma uma amostra real de licenças, condicionantes e documentos em uma visão governável: o que vence, o que falta, quem responde e qual evidência sustenta cada decisão.</p><Link className="button button--mint" href="/contato">Solicitar piloto <ArrowRight size={16} /></Link></div><aside><span className="status-chip status-chip--verified"><CheckCircle2 size={13} /> Piloto orientado a evidências</span><h2>O que será validado</h2><p>Licenças e condicionantes, pendências e prazos, responsáveis, evidências, revisão humana e planos de ação quando necessários.</p><div><MapPinned size={18} /><span>Uma amostra territorial real de sites</span></div><div><ShieldCheck size={18} /><span>Decisões críticas com aprovação humana</span></div><div><TowerControl size={18} /><span>Modelo repetível para operação distribuída</span></div></aside></section><section className="pilot-scope"><div><p className="eyebrow">Estrutura do piloto</p><h2>Uma prova de valor que a equipe consegue medir.</h2></div><div className="pilot-scope__grid"><article><span>Entrada</span><strong>50 sites, licenças existentes, planilhas, documentos e responsáveis.</strong></article><article><span>Regularizando</span><strong>Importação, normalização, pendências, evidências, responsáveis e dashboard.</strong></article><article><span>Resultado</span><strong>Cobertura documental, prazos, condicionantes críticas, evidências ausentes e ganhos de rotina.</strong></article></div></section><section className="pilot-phases"><div><p className="eyebrow">Quatro etapas</p><h2>Uma expansão só é segura quando o primeiro fluxo funciona.</h2></div><div>{phases.map((phase, index) => <article key={phase.title}><span><CircleDot size={15} /> 0{index + 1}</span><h3>{phase.title}</h3><p>{phase.body}</p></article>)}</div></section></main></div>;
}
