import MarketingNav from "@/components/MarketingNav";
import { Link } from "wouter";
import { ArrowRight, FileCheck2, ShieldCheck } from "lucide-react";
import { PRIVACY_CONTROLLER, PRIVACY_NOTICE_VERSION } from "@shared/privacy";

export default function PrivacyNotice() {
  return <div className="marketing-page"><MarketingNav /><main className="privacy-notice"><section className="privacy-notice__hero"><p className="eyebrow">Transparência de dados</p><h1>Aviso de <em>Privacidade</em></h1><p>Este aviso explica como o Regularizando trata dados pessoais no site e nas solicitações de piloto. Ele descreve a operação atual e será revisado por profissional jurídico antes do tratamento de dados de clientes em produção.</p><div className="privacy-notice__meta"><span>Versão {PRIVACY_NOTICE_VERSION}</span><span>Revisão jurídica pendente antes de clientes</span></div></section>

    <section className="privacy-notice__grid" aria-label="Resumo do Aviso de Privacidade"><article><ShieldCheck size={20} /><h2>Responsável atual</h2><p><strong>{PRIVACY_CONTROLLER.name}</strong>, {PRIVACY_CONTROLLER.description}. Esta identificação será atualizada caso a operação passe a ser conduzida por pessoa jurídica.</p></article><article><FileCheck2 size={20} /><h2>Canal de privacidade</h2><p>Use o <Link href="/contato">formulário de contato</Link>, selecione <strong>“Privacidade e dados pessoais / LGPD”</strong> e informe o pedido. Não envie documentos, credenciais ou dados sensíveis desnecessários.</p></article></section>

    <section className="privacy-notice__section"><h2>Dados e finalidades atuais</h2><p>O formulário pode receber nome, e-mail, empresa, função, setor, porte aproximado da operação e o contexto informado pelo remetente. Para solicitações de privacidade, recebe somente nome, e-mail, categoria do pedido e contexto suficiente para análise. O Regularizando solicita que documentos e dados sensíveis não sejam enviados pelo formulário.</p><div className="privacy-notice__table" role="region" aria-label="Finalidades de tratamento"><div className="privacy-notice__row privacy-notice__row--head"><strong>Finalidade</strong><strong>Dados mínimos</strong><strong>Base legal</strong></div><div className="privacy-notice__row"><span>Avaliar solicitação de piloto e responder ao contato.</span><span>Identificação e contexto comercial fornecidos.</span><span>Sujeita à revisão jurídica antes de produção com clientes.</span></div><div className="privacy-notice__row"><span>Receber e acompanhar pedido de privacidade.</span><span>Identificação, tipo de pedido e contexto.</span><span>Sujeita à revisão jurídica antes de produção com clientes.</span></div><div className="privacy-notice__row"><span>Proteger o serviço e manter rastreabilidade de segurança.</span><span>Metadados técnicos minimizados e eventos de governança.</span><span>Sujeita à revisão jurídica antes de produção com clientes.</span></div></div><p className="privacy-notice__note">O checkbox do formulário registra a manifestação de vontade para a finalidade apresentada. Ele não é apresentado como base legal universal para todos os tratamentos.</p></section>

    <section className="privacy-notice__section"><h2>Compartilhamento, armazenamento e segurança</h2><p>O Regularizando utiliza infraestrutura técnica gerenciada para autenticação, hospedagem, banco de dados, armazenamento de arquivos e registros minimizados de governança. Não vendemos dados pessoais. Os subprocessadores e termos aplicáveis a organizações clientes serão definidos e documentados contratualmente antes de um piloto com dados reais.</p><p>Os controles atualmente implementados incluem isolamento por organização, papéis de acesso, URLs temporárias condicionadas a autorização, auditoria de operações sensíveis, rate limiting compartilhado e quarentena estrutural de arquivos. Eles não equivalem a certificação, antivírus, SLA, RPO ou RTO.</p></section>

    <section className="privacy-notice__section"><h2>Retenção, direitos e decisões humanas</h2><p>O Regularizando mantém políticas de retenção versionadas por categoria e não executa exclusão automática. Pedidos de acesso, confirmação de tratamento, correção, exportação, exclusão, anonimização, oposição e dúvidas são avaliados por pessoa autorizada; uma solicitação de exclusão não determina apagamento imediato.</p><p>O pedido pode exigir avaliação de retenção legal, regulatória, contratual, auditoria ou defesa. Cada decisão deve ser registrada com justificativa e trilha de eventos. Para iniciar um pedido, <Link href="/contato">acesse o canal de privacidade</Link>.</p></section>

    <section className="privacy-notice__section"><h2>Atualizações deste aviso</h2><p>Quando houver mudança material de finalidade, controlador, canal de atendimento ou tecnologia relevante, esta página será atualizada com nova versão. A versão publicada é operacional e não substitui revisão jurídica independente.</p><p className="privacy-notice__legal">Referência: <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" target="_blank" rel="noreferrer">Lei nº 13.709/2018 (LGPD)</a>, especialmente os princípios de finalidade, necessidade, transparência e segurança.</p><Link className="button button--mint" href="/contato">Acessar o canal de privacidade <ArrowRight size={16} /></Link></section>
  </main></div>;
}
