import MarketingFooter from "@/components/MarketingFooter";
import MarketingNav from "@/components/MarketingNav";
import { ArrowRight, CheckCircle2, FileCheck2, Globe2, Radar, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const layers = [{ icon: Radar, title: "Núcleo: Licenciamento & Obrigações", body: "Requisitos, licenças, validade, condicionantes e prazos organizados por ativo e responsável." }, { icon: FileCheck2, title: "Evidências e revisão", body: "Arquivos, metadados, status de revisão e ligação direta com o registro que precisam comprovar." }, { icon: ShieldCheck, title: "Operação e não conformidades", body: "Inspeções, incidentes e planos de ação por prazo em uma linha do tempo operacional." }, { icon: Globe2, title: "Indicadores ambientais, ESG e GIS", body: "Indicadores com fonte e meta, conectados ao contexto territorial quando o módulo é adotado." }];

export default function Product() {
  return <div className="marketing-page"><MarketingNav /><main><section className="page-hero page-hero--product"><p className="eyebrow">O núcleo é o licenciamento</p><h1>Gestão ambiental começa quando cada obrigação encontra seu <em>responsável.</em></h1><p>O Regularizando centraliza licenças, condicionantes, documentos e prazos primeiro. Depois, a mesma base pode conectar operação, indicadores ambientais e território sem perder a origem de cada decisão.</p><Link href="/contato" className="button button--mint">Solicitar piloto <ArrowRight size={16} /></Link></section><section className="product-flow"><p className="eyebrow">O fluxo verificável</p><div><span>Obrigação</span><ArrowRight size={15} /><span>Requisito</span><ArrowRight size={15} /><span>Prazo</span><ArrowRight size={15} /><span>Responsável</span><ArrowRight size={15} /><span>Evidência</span><ArrowRight size={15} /><span>Revisão</span><ArrowRight size={15} /><span>Decisão</span></div></section><section className="product-grid">{layers.map((layer, index) => { const Icon = layer.icon; return <article key={layer.title}><span>0{index + 1}</span><Icon size={25} /><h2>{layer.title}</h2><p>{layer.body}</p><CheckCircle2 size={16} /></article>; })}</section></main><MarketingFooter /></div>;
}
