import MarketingNav from "@/components/MarketingNav";
import { ArrowRight, Bot, CheckCircle2, Clock3, Database, FileCheck2, FileKey2, Gauge, Link2, LockKeyhole, ShieldAlert, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

type ControlState = "Implementado" | "Em validação" | "Planejado";

const controls: Array<{ icon: typeof ShieldCheck; domain: string; title: string; state: ControlState; body: string }> = [
  { icon: LockKeyhole, domain: "Identidade e acesso", title: "Acesso autenticado e papéis organizacionais", state: "Implementado", body: "A plataforma usa autenticação OAuth e valida papéis organizacionais nas ações protegidas. A confirmação de MFA e verificação de e-mail continua dependente da configuração do provedor de identidade." },
  { icon: UsersRound, domain: "Isolamento de dados", title: "Fronteira por organização", state: "Implementado", body: "Entidades operacionais, decisões, evidências e pedidos de privacidade exigem organização ativa e validação de pertencimento no servidor." },
  { icon: FileCheck2, domain: "Documentos", title: "Quarentena e autorização humana", state: "Implementado", body: "Uploads passam por validação estrutural, hash de integridade e estados explícitos de quarentena. Processamento, vínculo como comprovante e download dependem de autorização humana registrada." },
  { icon: ShieldAlert, domain: "Documentos", title: "Antimalware e sandbox de terceiros", state: "Planejado", body: "O Regularizando não declara varredura antivírus, detecção de malware ou sandbox de arquivos. A validação atual é estrutural e não substitui essas camadas." },
  { icon: Gauge, domain: "Abuso e disponibilidade", title: "Limites compartilhados de requisição", state: "Implementado", body: "O controle de taxa usa buckets atômicos compartilhados por IP, usuário e organização, com resposta 429, Retry-After, auditoria minimizada e limpeza autenticada de buckets expirados." },
  { icon: Database, domain: "Auditoria e continuidade", title: "Trilha de decisões e réplica minimizada", state: "Implementado", body: "Ações sensíveis produzem eventos auditáveis e a réplica externa minimiza metadados. Rotinas contratuais de recuperação e objetivos RPO/RTO são definidos por piloto, não apresentados como SLA universal." },
  { icon: FileKey2, domain: "Privacidade", title: "Retenção e direitos LGPD", state: "Implementado", body: "Políticas são versionadas por categoria; pedidos de titulares usam referência pseudonimizada, justificativa humana, evidências de atendimento e não acionam exclusão automática." },
  { icon: Bot, domain: "IA", title: "Conteúdo documental não confiável", state: "Implementado", body: "Documentos não são tratados como instruções. Qualquer integração futura de IA deverá preservar escopo, não receber privilégios administrativos e nunca substituir revisão técnica humana." },
  { icon: Clock3, domain: "Continuidade", title: "Exercício operacional com parceiro", state: "Em validação", body: "Testes de restauração, canal de incidentes, acordo de tratamento e definição operacional de backup serão executados com cada parceiro autorizado de piloto." },
];

const stateClass: Record<ControlState, string> = { Implementado: "status-chip status-chip--verified", "Em validação": "status-chip status-chip--pendente", Planejado: "status-chip status-chip--vencida" };

export default function Security() {
  return <div className="marketing-page security-page"><MarketingNav /><main>
    <section className="security-hero"><p className="eyebrow">Trust Center</p><h1>Segurança, privacidade e limites <em>descritos como são.</em></h1><p>Este centro apresenta controles implementados, itens em validação e lacunas planejadas. Não afirma certificações, pentests, SLA, antivírus ou RPO/RTO que não tenham sido formalmente definidos e comprovados.</p><div className="flex flex-wrap gap-3"><Link className="button button--mint" href="/contato">Solicitar piloto <ArrowRight size={16} /></Link><a className="button button--outline" href="#controles">Ver controles</a></div></section>
    <section id="controles" className="security-controls"><div className="security-controls__intro"><p className="eyebrow">Matriz de controle</p><h2>Estado atual por domínio.</h2><p>O estado indica a maturidade do controle no produto, não uma promessa genérica de conformidade para todos os clientes.</p></div><div className="security-controls__grid">{controls.map(({ icon: Icon, domain, title, state, body }) => <article key={title}><span><Icon size={20} /></span><small className="eyebrow">{domain}</small><h3>{title}</h3><p>{body}</p><small className={stateClass[state]}><CheckCircle2 size={13} /> {state}</small></article>)}</div></section>
    <section className="security-transparency"><div><p className="eyebrow eyebrow--light">Validação técnica</p><h2>Fontes públicas, rastreabilidade e revisão.</h2></div><div><p>O Nível A de validação técnica foi concluído com documentos oficiais públicos, proveniência fonte → requisito e revisão humana. A rota detalhada de validação é administrativa, permanece protegida e não deve ser indexada por buscadores.</p><Link className="button button--outline" href="/validacao-tecnica">Abrir validação técnica restrita <Link2 size={16} /></Link></div></section>
    <section className="security-controls"><div className="security-controls__intro"><p className="eyebrow">Próximo passo responsável</p><h2>O que será acordado antes de dados reais.</h2></div><div className="security-controls__grid"><article><span><ShieldCheck size={20} /></span><h3>Escopo e DPA</h3><p>Finalidade, classes de dados, responsabilidades e base operacional serão acordadas com a organização parceira.</p></article><article><span><Database size={20} /></span><h3>Recuperação validada</h3><p>O parceiro definirá contato, rotina de backup/restauração, critérios de aceite e evidências do exercício.</p></article><article><span><UsersRound size={20} /></span><h3>Acesso inicial mínimo</h3><p>O piloto começará com usuários aprovados, convites rastreáveis e o menor conjunto de dados necessário.</p></article></div></section>
  </main></div>;
}
