import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, CheckCircle2, ClipboardCheck, FileText, Layers3, Plus, ShieldCheck } from "lucide-react";
import type { FormEvent } from "react";
import { useState } from "react";
import { Link } from "wouter";
import "./Obligations.css";

type Mode = "source" | "profile" | "requirement" | "version" | "applicability" | "conflict" | "resolveConflict" | null;
type Sector = "telecom" | "infraestrutura" | "industria" | "consultoria" | "outro";
const formatDate = (value: Date | null) => value ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Não informada";

export default function Sources() {
  const overview = trpc.obligations.overview.useQuery();
  const utils = trpc.useUtils();
  const [mode, setMode] = useState<Mode>(null);
  const [error, setError] = useState<string | null>(null);
  const refresh = () => void utils.obligations.overview.invalidate();
  const close = () => { setError(null); setMode(null); };
  const createSource = trpc.obligations.createSource.useMutation({ onSuccess: () => { refresh(); close(); } });
  const createProfile = trpc.obligations.createSectorProfile.useMutation({ onSuccess: () => { refresh(); close(); } });
  const createRequirement = trpc.obligations.createRequirement.useMutation({ onSuccess: () => { refresh(); close(); } });
  const createVersion = trpc.obligations.createVersion.useMutation({ onSuccess: () => { refresh(); close(); } });
  const reviewApplicability = trpc.obligations.reviewApplicability.useMutation({ onSuccess: () => { refresh(); close(); } });
  const createConflict = trpc.obligations.createSourceConflict.useMutation({ onSuccess: () => { refresh(); close(); } });
  const resolveConflict = trpc.obligations.resolveSourceConflict.useMutation({ onSuccess: () => { refresh(); close(); } });
  const updateOnboarding = trpc.obligations.updateOnboarding.useMutation({ onSuccess: refresh });
  const verifySource = trpc.obligations.verifySource.useMutation({ onSuccess: refresh });
  const verifyVersion = trpc.obligations.verifyVersion.useMutation({ onSuccess: refresh });
  const activateProfile = trpc.obligations.activateProfile.useMutation({ onSuccess: refresh });
  const data = overview.data;
  const failure = (reason: unknown) => setError(reason instanceof Error ? reason.message : "Não foi possível concluir a ação.");
  const date = (form: FormData, key: string) => form.get(key) ? new Date(`${String(form.get(key))}T12:00:00`).getTime() : undefined;

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    try {
      if (mode === "source") await createSource.mutateAsync({
        title: String(form.get("title")), issuer: String(form.get("issuer")), sourceType: String(form.get("sourceType")) as "norma",
        jurisdiction: String(form.get("jurisdiction") || "") || undefined, authorityLevel: String(form.get("authorityLevel")) as "federal",
        officialOriginStatus: String(form.get("originStatus")) as "oficial", identifier: String(form.get("identifier")),
        sourceVersionLabel: String(form.get("sourceVersion") || "") || undefined, sourceUrl: String(form.get("url") || "") || undefined,
        publicationDate: date(form, "publication"), effectiveFrom: date(form, "effectiveFrom"), effectiveTo: date(form, "effectiveTo"),
      });
      if (mode === "profile") await createProfile.mutateAsync({ sector: String(form.get("sector")) as Sector, name: String(form.get("name")), versionLabel: String(form.get("version")), scopeDescription: String(form.get("scope")) });
      if (mode === "requirement") await createRequirement.mutateAsync({
        sourceId: Number(form.get("source")), sectorProfileId: form.get("profile") ? Number(form.get("profile")) : undefined,
        code: String(form.get("code")), title: String(form.get("title")), applicabilityScope: String(form.get("scope")),
        applicabilityCriteria: String(form.get("criteria")), recurrenceLabel: String(form.get("recurrence") || "") || undefined,
        expectedEvidenceDescription: String(form.get("evidence") || "") || undefined,
      });
      if (mode === "version") await createVersion.mutateAsync({
        requirementId: Number(form.get("requirement")), versionLabel: String(form.get("version")), sourceLocator: String(form.get("locator")),
        sourceExcerpt: String(form.get("excerpt")), applicabilityCriteria: String(form.get("criteria")), recurrenceLabel: String(form.get("recurrence") || "") || undefined,
        expectedEvidenceDescription: String(form.get("evidence") || "") || undefined, interpretationNotes: String(form.get("notes") || "") || undefined,
        effectiveFrom: date(form, "effectiveFrom"), effectiveTo: date(form, "effectiveTo"),
      });
      if (mode === "applicability") await reviewApplicability.mutateAsync({ requirementId: Number(form.get("requirement")), status: String(form.get("status")) as "aplicavel_confirmada", rationale: String(form.get("rationale")) });
      if (mode === "conflict") await createConflict.mutateAsync({ primarySourceId: Number(form.get("primarySource")), conflictingSourceId: Number(form.get("conflictingSource")), conflictTopic: String(form.get("topic")), hierarchyNote: String(form.get("hierarchy")) });
      if (mode === "resolveConflict") await resolveConflict.mutateAsync({ conflictId: Number(form.get("conflict")), status: String(form.get("status")) as "resolvido", rationale: String(form.get("rationale")) });
    } catch (reason) { failure(reason); }
  }

  if (overview.isLoading) return <DashboardLayout><div className="dashboard-loading">Carregando fontes e versões…</div></DashboardLayout>;

  const onboarding = data?.onboarding ?? { sourceCatalogReady: false, assetContextReady: false, evidencePackageReady: false, technicalReviewReady: false, currentStep: "fontes" as const };
  const saveOnboarding = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void updateOnboarding.mutateAsync({ sourceCatalogReady: form.get("sourceCatalogReady") === "on", assetContextReady: form.get("assetContextReady") === "on", evidencePackageReady: form.get("evidencePackageReady") === "on", technicalReviewReady: form.get("technicalReviewReady") === "on", currentStep: String(form.get("currentStep")) as "fontes" }).catch(failure); };

  return <DashboardLayout><main className="obligation-page">
    <header className="dashboard-page__header obligation-header"><div><p className="kicker">Base documental / conhecimento controlado</p><h1>Fontes e requisitos</h1><p className="dashboard-subtitle">A plataforma registra fonte, vigência, localização exata do texto e decisão humana de aplicabilidade. Perfis setoriais apenas filtram contexto — não interpretam normas sozinhos.</p></div><div className="dashboard-header-actions"><Link href="/obrigacoes" className="button button--outline">Ver obrigações</Link><button type="button" className="button button--dark" onClick={() => { setError(null); setMode("source"); }}><Plus size={16} /> Nova fonte</button></div></header>
    {!data ? <section className="dashboard-card"><p>Crie um espaço de trabalho para começar a registrar fontes.</p></section> : <div className="sources-grid">
      <section className="dashboard-card sources-card sources-card--wide"><div className="card-heading"><div><span className="kicker">Onboarding do primeiro caso</span><h2>Prontidão documental, sem dados simulados</h2></div><Layers3 size={21} /></div><p className="empty-copy">Conclua cada etapa apenas quando o documento ou dado real do ativo estiver disponível. A plataforma não transforma este checklist em obrigação nem em conclusão jurídica.</p><details className="onboarding-documents"><summary>Documentos reais solicitados para o primeiro ativo</summary><p>Envie, preferencialmente para o mesmo empreendimento ou ativo, a licença ambiental vigente e seus anexos, a relação completa de condicionantes, parecer técnico ou decisão do órgão, protocolo de renovação quando houver, cadastro do ativo, município, UF e coordenadas geográficas.</p><p>Inclua também laudos usados como evidência, fotografia ou documento operacional, pendência ou não conformidade conhecida, plano de ação relacionado e histórico disponível de revisão ou aprovação.</p></details><form className="onboarding-form" onSubmit={saveOnboarding}><label><input name="sourceCatalogReady" type="checkbox" defaultChecked={onboarding.sourceCatalogReady} /> Fontes oficiais ou documentos organizacionais cadastrados</label><label><input name="assetContextReady" type="checkbox" defaultChecked={onboarding.assetContextReady} /> Ativo identificado com município, UF e coordenadas quando disponíveis</label><label><input name="evidencePackageReady" type="checkbox" defaultChecked={onboarding.evidencePackageReady} /> Licença, anexos, condicionantes e evidências reunidos</label><label><input name="technicalReviewReady" type="checkbox" defaultChecked={onboarding.technicalReviewReady} /> Pronto para revisão técnica humana</label><div className="inline-actions"><label>Etapa atual<select name="currentStep" defaultValue={onboarding.currentStep}><option value="fontes">Fontes</option><option value="ativo">Ativo</option><option value="evidencias">Evidências</option><option value="revisao">Revisão</option></select></label><button className="button button--outline button--small" type="submit" disabled={updateOnboarding.isPending}>Atualizar progresso</button></div></form></section>
      <section className="dashboard-card sources-card"><div className="card-heading"><div><span className="kicker">1. Documento de origem</span><h2>Fontes normativas e operacionais</h2></div><BookOpenCheck size={21} /></div>{data.sources.length === 0 ? <p className="empty-copy">Nenhuma fonte cadastrada. Não há requisitos predefinidos: a base deve partir de documentos reais e rastreáveis do piloto.</p> : <div className="source-list">{data.sources.map((source) => <article className="source-row" key={source.id}><div><strong>{source.identifier}</strong><p>{source.title}</p><small>{source.issuer} · {source.jurisdiction ?? "jurisdição pendente"} · {source.authorityLevel} · origem: {source.officialOriginStatus}</small><small>vigência: {formatDate(source.effectiveFrom)} — {formatDate(source.effectiveTo)}</small></div><div><span className={`status-chip ${source.verificationStatus === "verificada" ? "status-chip--verified" : "status-chip--pendente"}`}>{source.verificationStatus}</span>{source.verificationStatus !== "verificada" && <button type="button" className="text-action" disabled={verifySource.isPending} onClick={() => void verifySource.mutateAsync({ sourceId: source.id }).catch(failure)}>Verificar</button>}</div></article>)}</div>}</section>
      <section className="dashboard-card sources-card"><div className="card-heading"><div><span className="kicker">2. Filtro contextual</span><h2>Perfis setoriais</h2></div><button type="button" className="icon-action" aria-label="Novo perfil setorial" onClick={() => { setError(null); setMode("profile"); }}><Plus size={16} /></button></div>{data.profiles.length === 0 ? <p className="empty-copy">Crie um perfil versionado para delimitar vocabulário e limites de telecom, infraestrutura, indústria, consultoria ou outro contexto.</p> : <div className="source-list">{data.profiles.map((profile) => <article className="source-row" key={profile.id}><div><strong>{profile.name}</strong><p>{profile.sector} · versão {profile.versionLabel}</p><small>{profile.scopeDescription}</small></div><div><span className={`status-chip ${profile.status === "ativo" ? "status-chip--verified" : "status-chip--pendente"}`}>{profile.status}</span>{profile.status !== "ativo" && <button className="text-action" type="button" disabled={activateProfile.isPending} onClick={() => void activateProfile.mutateAsync({ profileId: profile.id }).catch(failure)}>Ativar</button>}</div></article>)}</div>}</section>
      <section className="dashboard-card sources-card sources-card--wide"><div className="card-heading"><div><span className="kicker">3. Requisito, versão e aplicabilidade</span><h2>Trechos que podem seguir para revisão</h2></div><div className="inline-actions"><button type="button" className="button button--outline button--small" onClick={() => { setError(null); setMode("requirement"); }}>Novo requisito</button><button type="button" className="button button--outline button--small" onClick={() => { setError(null); setMode("applicability"); }}>Revisar aplicabilidade</button><button type="button" className="button button--dark button--small" onClick={() => { setError(null); setMode("version"); }}>Nova versão</button></div></div>{data.requirements.length === 0 ? <p className="empty-copy">Aplique requisitos apenas após documentar os critérios de aplicação. Sem essa revisão, o motor mostra “Aplicabilidade pendente de revisão técnica”.</p> : <div className="version-list">{data.requirements.map((requirement) => <article className="version-row" key={requirement.id}><ClipboardCheck size={17} /><div><strong>{requirement.code} · {requirement.title}</strong><p>{requirement.applicabilityStatus.replaceAll("_", " ")}</p><small>Critérios: {requirement.applicabilityCriteria}</small>{requirement.expectedEvidenceDescription && <small>Evidência esperada: {requirement.expectedEvidenceDescription}</small>}</div><span className={`status-chip ${requirement.applicabilityStatus === "aplicavel_confirmada" ? "status-chip--verified" : "status-chip--pendente"}`}>{requirement.applicabilityStatus}</span></article>)}</div>}</section>
      <section className="dashboard-card sources-card sources-card--wide"><div className="card-heading"><div><span className="kicker">Conflitos de fontes</span><h2>Não decidir silenciosamente</h2></div><div className="inline-actions"><button type="button" className="button button--outline button--small" onClick={() => { setError(null); setMode("conflict"); }}>Registrar conflito</button><button type="button" className="button button--dark button--small" onClick={() => { setError(null); setMode("resolveConflict"); }}>Revisar conflito</button></div></div>{data.conflicts.length === 0 ? <p className="empty-copy">Nenhum conflito registrado. Quando duas fontes divergirem, registre ambas, sua hierarquia e vigência antes de qualquer decisão.</p> : <div className="source-list">{data.conflicts.map((conflict) => <article className="source-row" key={conflict.id}><div><strong>{conflict.conflictTopic}</strong><p>Fontes #{conflict.primarySourceId} e #{conflict.conflictingSourceId}</p><small>{conflict.hierarchyNote}</small></div><span className={`status-chip ${conflict.status === "resolvido" ? "status-chip--verified" : "status-chip--pendente"}`}>{conflict.status}</span></article>)}</div>}</section>
      <section className="dashboard-card sources-card sources-card--wide"><div className="card-heading"><div><span className="kicker">4. Texto versionado</span><h2>Versões revisáveis</h2></div><FileText size={21} /></div>{data.versions.length === 0 ? <p className="empty-copy">Toda versão deve trazer artigo, item ou página, texto original, vigência e revisão antes de sustentar uma obrigação.</p> : <div className="version-list">{data.versions.map((version) => { const requirement = data.requirements.find((item) => item.id === version.requirementId); return <article className="version-row" key={version.id}><FileText size={17} /><div><strong>{requirement?.code ?? "Requisito"} · v{version.versionLabel}</strong><p>{requirement?.title}</p><small>{version.sourceLocator} · {version.sourceExcerpt.slice(0, 130)}{version.sourceExcerpt.length > 130 ? "…" : ""}</small></div><div><span className={`status-chip ${version.reviewStatus === "verificada" ? "status-chip--verified" : "status-chip--pendente"}`}>{version.reviewStatus}</span>{version.reviewStatus !== "verificada" && <button type="button" className="text-action" disabled={verifyVersion.isPending} onClick={() => void verifyVersion.mutateAsync({ versionId: version.id }).catch(failure)}>Revisar e verificar</button>}</div></article>; })}</div>}</section>
    </div>}
    {mode && <div className="entry-backdrop" role="presentation" onClick={close}><section className="entry-panel obligation-dialog" role="dialog" aria-modal="true" aria-labelledby="source-dialog-title" onClick={(event) => event.stopPropagation()}><button className="entry-close" type="button" aria-label="Fechar" onClick={close}>×</button><form className="entry-form" onSubmit={submit}>
      {mode === "source" && <><span className="kicker">Documento de origem</span><h2 id="source-dialog-title">Cadastrar fonte</h2><label>Identificador<input required name="identifier" placeholder="Ex.: Lei Federal nº 15.190/2025" /></label><label>Título<input required name="title" placeholder="Nome oficial do documento" /></label><label>Órgão emissor<input required name="issuer" placeholder="Órgão emissor oficial" /></label><label>Jurisdição<input name="jurisdiction" placeholder="Ex.: Federal; Estado de São Paulo" /></label><div className="form-row"><label>Nível de autoridade<select name="authorityLevel"><option value="federal">Federal</option><option value="estadual">Estadual</option><option value="municipal">Municipal</option><option value="setorial">Setorial</option><option value="organizacional">Organizacional</option><option value="outro">Outro</option></select></label><label>Origem<select name="originStatus"><option value="oficial">Publicação oficial</option><option value="documento_organizacao">Documento da organização</option><option value="pendente">Pendente de classificação</option></select></label></div><label>Tipo<select name="sourceType"><option value="norma">Norma</option><option value="licenca">Licença</option><option value="condicionante">Condicionante</option><option value="termo_referencia">Termo de referência</option><option value="oficio">Ofício</option><option value="orientacao_tecnica">Orientação técnica</option></select></label><label>Versão da fonte <small>opcional</small><input name="sourceVersion" placeholder="Texto compilado em 2026" /></label><label>URL de origem<input required name="url" type="url" placeholder="https://" /></label><div className="form-row"><label>Publicação<input name="publication" type="date" /></label><label>Início da vigência<input name="effectiveFrom" type="date" /></label><label>Fim da vigência<input name="effectiveTo" type="date" /></label></div></>}
      {mode === "profile" && <><span className="kicker">Contexto controlado</span><h2 id="source-dialog-title">Criar perfil setorial</h2><label>Setor<select name="sector"><option value="telecom">Telecom</option><option value="infraestrutura">Infraestrutura</option><option value="industria">Indústria</option><option value="consultoria">Consultoria</option><option value="outro">Outro</option></select></label><label>Nome<input required name="name" placeholder="Ex.: Sites distribuídos em telecom" /></label><label>Versão<input required name="version" placeholder="1.0" /></label><label>Escopo do perfil<textarea required minLength={12} name="scope" placeholder="Defina vocabulário e limites. O perfil não interpreta normas autonomamente." /></label></>}
      {mode === "requirement" && <><span className="kicker">Requisito rastreável</span><h2 id="source-dialog-title">Criar requisito</h2><label>Fonte<select required name="source"><option value="">Selecione uma fonte</option>{data?.sources.map((item) => <option value={item.id} key={item.id}>{item.identifier} · {item.title}</option>)}</select></label><label>Perfil setorial ativo<select name="profile"><option value="">Sem perfil específico</option>{data?.profiles.filter((item) => item.status === "ativo").map((item) => <option value={item.id} key={item.id}>{item.name} · v{item.versionLabel}</option>)}</select></label><label>Código<input required name="code" placeholder="Ex.: LIC-LO-001" /></label><label>Título<input required name="title" placeholder="Descrição objetiva do requisito" /></label><label>Escopo aplicável<textarea required minLength={12} name="scope" placeholder="Delimite atividade, local e condições de aplicação." /></label><label>Critérios de aplicabilidade<textarea required minLength={12} name="criteria" placeholder="Registre os fatos e documentos necessários para confirmar ou rejeitar a aplicação." /></label><label>Frequência <small>opcional</small><input name="recurrence" placeholder="Ex.: anual; por renovação; conforme condicionante" /></label><label>Evidência esperada <small>opcional</small><textarea name="evidence" placeholder="Ex.: licença vigente, protocolo, laudo, foto operacional ou relatório." /></label></>}
      {mode === "applicability" && <><span className="kicker">Decisão humana obrigatória</span><h2 id="source-dialog-title">Revisar aplicabilidade</h2><label>Requisito<select required name="requirement"><option value="">Selecione um requisito</option>{data?.requirements.map((item) => <option value={item.id} key={item.id}>{item.code} · {item.title}</option>)}</select></label><label>Status<select name="status"><option value="aplicavel_confirmada">Aplicável confirmada</option><option value="nao_aplicavel">Não aplicável</option></select></label><label>Justificativa técnica<textarea required minLength={12} name="rationale" placeholder="Cite o ativo, escopo e documentos considerados. Não escreva uma conclusão sem base documental." /></label></>}
      {mode === "conflict" && <><span className="kicker">Divergência rastreável</span><h2 id="source-dialog-title">Registrar conflito entre fontes</h2><label>Fonte principal<select required name="primarySource"><option value="">Selecione uma fonte</option>{data?.sources.map((item) => <option value={item.id} key={item.id}>{item.identifier}</option>)}</select></label><label>Fonte potencialmente conflitante<select required name="conflictingSource"><option value="">Selecione outra fonte</option>{data?.sources.map((item) => <option value={item.id} key={item.id}>{item.identifier}</option>)}</select></label><label>Tema da divergência<input required name="topic" minLength={8} placeholder="Ex.: competência licenciadora; vigência; condicionante" /></label><label>Hierarquia e vigência observadas<textarea required minLength={12} name="hierarchy" placeholder="Registre as duas fontes, o ponto de possível conflito e a hierarquia/vigência conhecida. Não escolha uma delas aqui." /></label></>}
      {mode === "resolveConflict" && <><span className="kicker">Revisão técnica humana</span><h2 id="source-dialog-title">Revisar conflito</h2><label>Conflito<select required name="conflict"><option value="">Selecione um conflito</option>{data?.conflicts.filter((item) => item.status === "pendente_revisao").map((item) => <option value={item.id} key={item.id}>{item.conflictTopic}</option>)}</select></label><label>Status<select name="status"><option value="resolvido">Resolvido</option><option value="nao_aplicavel">Não aplicável</option></select></label><label>Fundamentação da revisão<textarea required minLength={12} name="rationale" placeholder="Explique a decisão, citando hierarquia, vigência e fonte exata. Esta justificativa será auditável." /></label></>}
      {mode === "version" && <><span className="kicker">Versão revisável</span><h2 id="source-dialog-title">Adicionar versão</h2><label>Requisito<select required name="requirement"><option value="">Selecione um requisito</option>{data?.requirements.map((item) => <option value={item.id} key={item.id}>{item.code} · {item.title}</option>)}</select></label><label>Rótulo de versão<input required name="version" placeholder="2026.1" /></label><label>Artigo, item ou página<input required name="locator" placeholder="Ex.: art. 14, § 2º; p. 8; condicionante 3.2" /></label><label>Texto original<textarea required minLength={12} name="excerpt" placeholder="Transcreva o trecho documental que fundamenta esta versão." /></label><label>Critérios de aplicabilidade desta versão<textarea required minLength={12} name="criteria" placeholder="Registre os fatos e documentos necessários para aplicar esta redação específica." /></label><label>Frequência <small>opcional</small><input name="recurrence" placeholder="Ex.: anual; por renovação; conforme condicionante" /></label><label>Evidência esperada <small>opcional</small><textarea name="evidence" placeholder="Ex.: licença, protocolo, laudo, foto ou relatório aplicável à versão." /></label><label>Notas de interpretação <small>opcional</small><textarea name="notes" placeholder="Apenas contexto operacional; não substitui a fonte ou a revisão." /></label><div className="form-row"><label>Início da vigência<input name="effectiveFrom" type="date" /></label><label>Fim da vigência<input name="effectiveTo" type="date" /></label></div></>}
      {error && <p className="form-error">{error}</p>}<button className="button button--dark" type="submit">Salvar como rascunho</button>
    </form></section></div>}
  </main></DashboardLayout>;
}
