import MarketingNav from "@/components/MarketingNav";
import { ArrowRight, CheckCircle2, ClipboardCheck, Globe2, Leaf, ShieldCheck, TowerControl } from "lucide-react";
import { Link } from "wouter";

const useCases = [
  { icon: TowerControl, tag: "Telecom / sites distribuídos", title: "Evite que uma licença local vire um risco nacional.", problem: "Em portfólios com muitos sites, prazos, condicionantes, documentos e responsáveis ficam espalhados entre equipes regionais, fornecedores e planilhas.", flow: ["Inventarie cada site por código, município, estágio e risco.", "Associe licenças, condicionantes e validade ao ativo correto.", "Atribua CAPAs a responsáveis e valide evidência antes da conclusão."], outcome: "A gestão passa a enxergar exceções, vencimentos e pendências por região sem perder o vínculo com a fonte." },
  { icon: ClipboardCheck, tag: "Infraestrutura e obras", title: "Transforme condicionantes em rotina de obra.", problem: "A condicionante nasce na licença, mas a execução acontece com frentes, contratadas e prazos diferentes. O desvio costuma aparecer tarde, quando a evidência já não está completa.", flow: ["Desdobre cada condicionante em ação, evidência e responsável.", "Registre inspeções, desvios e ações corretivas no mesmo contexto.", "Mantenha o histórico pronto para a renovação ou fiscalização."], outcome: "O canteiro deixa de tratar a conformidade como arquivo final e passa a conduzi-la como rotina operacional." },
  { icon: Leaf, tag: "ESG para grandes empresas", title: "Leve o número ESG até o dado que o sustenta.", problem: "Indicadores consolidados chegam ao relatório sem unidade, período, fonte ou critério de revisão consistentes, tornando assurance e comparabilidade mais difíceis.", flow: ["Defina métrica, unidade, período, meta e responsável.", "Vincule a fonte e a evidência que sustentam cada valor.", "Revise o dado antes de classificá-lo como verificado."], outcome: "O painel ESG se torna uma cadeia de dados auditável, e não apenas um conjunto de slides de reporte." },
  { icon: ShieldCheck, tag: "EHS e contratadas", title: "Conecte quase acidentes à ação que evita a recorrência.", problem: "Ocorrências, permissões, treinamentos e não conformidades são registradas em canais diferentes; a investigação perde contexto e a CAPA não chega ao encerramento validado.", flow: ["Registre incidente, quase acidente ou condição insegura.", "Abra CAPA com prioridade, prazo e responsável.", "Anexe evidência de execução e conduza a revisão humana."], outcome: "A equipe obtém uma linha de tempo objetiva entre o evento, a ação e a verificação de eficácia." },
];

export default function UseCases() {
  return <div className="marketing-page"><MarketingNav /><main><section className="page-hero"><p className="eyebrow">Casos de uso detalhados</p><h1>Onde a complexidade ambiental se torna uma <em>rotina verificável.</em></h1><p>Estes cenários representam dores recorrentes de operações distribuídas. O fluxo deve ser configurado com as obrigações e dados reais de cada organização.</p></section><section className="use-case-list">{useCases.map((item, index) => { const Icon = item.icon; return <article className="use-case-card" key={item.tag}><div className="use-case-card__lead"><span className="use-case-number">0{index + 1}</span><Icon size={24} /><span className="eyebrow">{item.tag}</span><h2>{item.title}</h2><p>{item.problem}</p></div><div className="use-case-card__flow"><span className="kicker">Como o sistema atua</span>{item.flow.map((step, stepIndex) => <div key={step}><span>{stepIndex + 1}</span><p>{step}</p></div>)}</div><div className="use-case-card__outcome"><CheckCircle2 size={18} /><p>{item.outcome}</p></div></article>; })}</section><section className="page-cta"><Globe2 size={25} /><div><p className="eyebrow eyebrow--light">Comece pelo cenário que exige mais atenção</p><h2>Transforme um caso real em seu primeiro fluxo.</h2></div><Link href="/piloto-telecom" className="button button--mint">Desenhar piloto <ArrowRight size={16} /></Link></section></main></div>;
}
