import { createHash, randomBytes, randomUUID } from "node:crypto";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { ENV } from "./_core/env";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import {
  acceptOrganizationInvite,
  activateSectorProfile,
  assertEntityBelongsToOrganization,
  assignCapaResponsible,
  assignObligationResponsible,
  assignReviewResponsible,
  createCapaAction,
  createAuditEvent,
  createCondition,
  createEsgMetric,
  createEvidence,
  createIncident,
  createLicense,
  createObligationInstance,
  createOrganizationForUser,
  createOrganizationInvite,
  createPilotRequest,
  createRequirement,
  createRequirementSource,
  createRequirementVersion,
  createReviewRequest,
  createSectorProfile,
  createSite,
  decideObligation,
  decideReviewRequest,
  getDashboardData,
  getEvidenceForOrganization,
  getInviteByHash,
  getMemberOfOrganizationByEmail,
  getOrganizationForUser,
  getObligationOverview,
  getRequirementApplicationContext,
  getRequirementForOrganization,
  getRequirementVersionForOrganization,
  getSectorProfileForOrganization,
  getSourceForOrganization,
  getTeamOverview,
  linkEvidenceToObligation,
  revokeOrganizationInvite,
  verifyRequirementSource,
  verifyRequirementVersion,
  type OwnedEntityType,
} from "./db";
import { storageGetSignedUrl, storagePut } from "./storage";
import { canManageTeam, canReviewEvidence, normalizeInvitationEmail, requireWorkspaceContext } from "./regularizando.policy";
import { makeOrganizationSlug, safeEvidenceName, validateEvidenceUpload } from "./regularizando.validation";

const organizationInput = z.object({ name: z.string().trim().min(3).max(160), sector: z.enum(["telecom", "infraestrutura", "industria", "consultoria", "outro"]) });
const entityType = z.enum(["licenca", "condicionante", "capa", "incidente", "esg", "site", "outro"]);
const invitationRole = z.enum(["admin", "analyst", "reviewer", "viewer"]);
const sector = z.enum(["telecom", "infraestrutura", "industria", "consultoria", "outro"]);
const sourceType = z.enum(["norma", "licenca", "condicionante", "termo_referencia", "oficio", "orientacao_tecnica", "outro"]);
const obligationDecision = z.enum(["cumprida", "nao_cumprida", "nao_aplicavel", "requer_revisao"]);
const safeOrigin = z.string().url().refine((value) => { const parsed = new URL(value); return ["http:", "https:"].includes(parsed.protocol) && parsed.origin === value; }, "Origem de convite inválida.");
const hashInviteToken = (token: string) => createHash("sha256").update(token).digest("hex");
async function getRequiredOrganization(userId: number) { return requireWorkspaceContext(await getOrganizationForUser(userId)); }
function requireTeamManager(role: string) { if (!canManageTeam(role)) throw new TRPCError({ code: "FORBIDDEN", message: "Seu perfil não pode gerenciar a equipe." }); }
function requireTechnicalReviewer(role: string) { if (!canReviewEvidence(role)) throw new TRPCError({ code: "FORBIDDEN", message: "Esta ação exige revisão técnica humana autorizada." }); }

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(({ ctx }) => ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  organization: router({
    current: protectedProcedure.query(({ ctx }) => getOrganizationForUser(ctx.user.id)),
    create: protectedProcedure.input(organizationInput).mutation(async ({ ctx, input }) => { if (ctx.user.openId !== ENV.ownerOpenId) throw new TRPCError({ code: "FORBIDDEN", message: "O piloto é privado; solicite um convite ao administrador." }); const existing = await getOrganizationForUser(ctx.user.id); if (existing) return existing.organization; const organization = await createOrganizationForUser({ ...input, slug: `${makeOrganizationSlug(input.name)}-${randomUUID().slice(0, 6)}`, userId: ctx.user.id }); await createAuditEvent({ organizationId: organization.id, actorUserId: ctx.user.id, action: "ORGANIZATION_CREATED", resourceType: "organization", resourceId: organization.id, metadata: JSON.stringify({ sector: organization.sector }) }); return organization; }),
  }),
  pilot: router({
    request: publicProcedure.input(z.object({ name: z.string().trim().min(2).max(160), email: z.string().trim().email().max(320), company: z.string().trim().min(2).max(180), role: z.string().trim().max(120).optional(), sector: z.enum(["telecom", "infraestrutura", "industria", "consultoria", "outro"]), portfolioSize: z.string().trim().max(80).optional(), challenge: z.string().trim().min(10).max(2000).optional(), consent: z.literal(true) })).mutation(async ({ input }) => {
      const id = await createPilotRequest({ name: input.name, email: input.email.toLowerCase(), company: input.company, role: input.role || null, sector: input.sector, portfolioSize: input.portfolioSize || null, challenge: input.challenge || null, consentedAt: new Date() });
      return { id, success: true } as const;
    }),
  }),
  dashboard: router({ overview: protectedProcedure.query(async ({ ctx }) => { const context = await getOrganizationForUser(ctx.user.id); return context ? { organization: context.organization, membership: context.membership, data: await getDashboardData(context.organization.id) } : { organization: null, data: null }; }) }),
  obligations: router({
    overview: protectedProcedure.query(async ({ ctx }) => { const org = await getRequiredOrganization(ctx.user.id); return getObligationOverview(org.organization.id); }),
    createSectorProfile: protectedProcedure.input(z.object({ sector, name: z.string().trim().min(3).max(160), versionLabel: z.string().trim().min(1).max(48), scopeDescription: z.string().trim().min(12).max(4000) })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); const id = await createSectorProfile({ ...input, organizationId: org.organization.id, createdByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "SECTOR_PROFILE_CREATED", resourceType: "sector_profile", resourceId: id, metadata: JSON.stringify({ sector: input.sector, versionLabel: input.versionLabel }) }); return id; }),
    activateProfile: protectedProcedure.input(z.object({ profileId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); await activateSectorProfile({ profileId: input.profileId, organizationId: org.organization.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "SECTOR_PROFILE_ACTIVATED", resourceType: "sector_profile", resourceId: input.profileId, metadata: null }); return { success: true } as const; }),
    createSource: protectedProcedure.input(z.object({ title: z.string().trim().min(3).max(260), issuer: z.string().trim().min(2).max(180), sourceType, identifier: z.string().trim().min(2).max(180), sourceUrl: z.string().url().max(700).optional(), publicationDate: z.number().int().optional(), effectiveFrom: z.number().int().optional(), effectiveTo: z.number().int().optional() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); const id = await createRequirementSource({ ...input, organizationId: org.organization.id, sourceUrl: input.sourceUrl ?? null, publicationDate: input.publicationDate ? new Date(input.publicationDate) : null, effectiveFrom: input.effectiveFrom ? new Date(input.effectiveFrom) : null, effectiveTo: input.effectiveTo ? new Date(input.effectiveTo) : null, createdByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "REQUIREMENT_SOURCE_CREATED", resourceType: "requirement_source", resourceId: id, metadata: JSON.stringify({ sourceType: input.sourceType, identifier: input.identifier }) }); return id; }),
    verifySource: protectedProcedure.input(z.object({ sourceId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTechnicalReviewer(org.membership.role); await verifyRequirementSource({ sourceId: input.sourceId, organizationId: org.organization.id, reviewerUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "REQUIREMENT_SOURCE_VERIFIED", resourceType: "requirement_source", resourceId: input.sourceId, metadata: null }); return { success: true } as const; }),
    createRequirement: protectedProcedure.input(z.object({ sourceId: z.number().int().positive(), sectorProfileId: z.number().int().positive().optional(), code: z.string().trim().min(2).max(100), title: z.string().trim().min(3).max(260), applicabilityScope: z.string().trim().min(12).max(4000) })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); await getSourceForOrganization(input.sourceId, org.organization.id); if (input.sectorProfileId) { const overview = await getObligationOverview(org.organization.id); if (!overview.profiles.some((profile) => profile.id === input.sectorProfileId && profile.status === "ativo")) throw new Error("O perfil setorial deve estar ativo e pertencer à organização atual."); } const id = await createRequirement({ ...input, sectorProfileId: input.sectorProfileId ?? null, organizationId: org.organization.id, createdByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "REQUIREMENT_CREATED", resourceType: "requirement", resourceId: id, metadata: JSON.stringify({ sourceId: input.sourceId, code: input.code }) }); return id; }),
    createVersion: protectedProcedure.input(z.object({ requirementId: z.number().int().positive(), versionLabel: z.string().trim().min(1).max(48), sourceExcerpt: z.string().trim().min(12).max(12000), interpretationNotes: z.string().trim().max(4000).optional(), effectiveFrom: z.number().int().optional(), effectiveTo: z.number().int().optional() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); await getRequirementForOrganization(input.requirementId, org.organization.id); const id = await createRequirementVersion({ ...input, organizationId: org.organization.id, interpretationNotes: input.interpretationNotes ?? null, effectiveFrom: input.effectiveFrom ? new Date(input.effectiveFrom) : null, effectiveTo: input.effectiveTo ? new Date(input.effectiveTo) : null, createdByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "REQUIREMENT_VERSION_CREATED", resourceType: "requirement_version", resourceId: id, metadata: JSON.stringify({ requirementId: input.requirementId, versionLabel: input.versionLabel }) }); return id; }),
    verifyVersion: protectedProcedure.input(z.object({ versionId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTechnicalReviewer(org.membership.role); await verifyRequirementVersion({ versionId: input.versionId, organizationId: org.organization.id, reviewerUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "REQUIREMENT_VERSION_VERIFIED", resourceType: "requirement_version", resourceId: input.versionId, metadata: null }); return { success: true } as const; }),
    applyRequirement: protectedProcedure.input(z.object({ requirementVersionId: z.number().int().positive(), siteId: z.number().int().positive().optional(), licenseId: z.number().int().positive().optional(), scopeJustification: z.string().trim().min(12).max(4000), scopeConfirmed: z.literal(true), dueDate: z.number().int().optional() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); if (input.siteId) await assertEntityBelongsToOrganization(org.organization.id, "site", input.siteId); if (input.licenseId) await assertEntityBelongsToOrganization(org.organization.id, "licenca", input.licenseId); const id = await createObligationInstance({ requirementVersionId: input.requirementVersionId, scopeJustification: input.scopeJustification, organizationId: org.organization.id, siteId: input.siteId ?? null, licenseId: input.licenseId ?? null, dueDate: input.dueDate ? new Date(input.dueDate) : null, createdByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "OBLIGATION_APPLIED", resourceType: "obligation", resourceId: id, metadata: JSON.stringify({ requirementVersionId: input.requirementVersionId, scopeConfirmed: input.scopeConfirmed }) }); return id; }),
    assignResponsible: protectedProcedure.input(z.object({ obligationId: z.number().int().positive(), responsibleUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); await assignObligationResponsible({ ...input, organizationId: org.organization.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "OBLIGATION_RESPONSIBLE_ASSIGNED", resourceType: "obligation", resourceId: input.obligationId, metadata: JSON.stringify({ responsibleUserId: input.responsibleUserId }) }); return { success: true } as const; }),
    linkEvidence: protectedProcedure.input(z.object({ obligationId: z.number().int().positive(), evidenceId: z.number().int().positive(), evidenceRole: z.enum(["comprovacao", "fonte", "complemento"]).default("comprovacao") })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); const id = await linkEvidenceToObligation({ ...input, organizationId: org.organization.id, linkedByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "OBLIGATION_EVIDENCE_LINKED", resourceType: "obligation", resourceId: input.obligationId, metadata: JSON.stringify({ evidenceId: input.evidenceId, evidenceRole: input.evidenceRole }) }); return id; }),
    decide: protectedProcedure.input(z.object({ obligationId: z.number().int().positive(), requirementVersionId: z.number().int().positive(), decision: obligationDecision, rationale: z.string().trim().min(12).max(6000) })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTechnicalReviewer(org.membership.role); const id = await decideObligation({ ...input, organizationId: org.organization.id, decidedByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "OBLIGATION_DECIDED", resourceType: "obligation", resourceId: input.obligationId, metadata: JSON.stringify({ decisionId: id, decision: input.decision, requirementVersionId: input.requirementVersionId }) }); return id; }),
    analysisGate: protectedProcedure.input(z.object({ requirementVersionId: z.number().int().positive() })).query(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); const context = await getRequirementApplicationContext(input.requirementVersionId, org.organization.id); const fontes = [{ id: context.source.id, titulo: context.source.title, identificador: context.source.identifier, status: context.source.verificationStatus, url: context.source.sourceUrl }]; const limitesDeEscopo = context.requirement.applicabilityScope; const perfilSetorial = context.profile ? { id: context.profile.id, nome: context.profile.name, versao: context.profile.versionLabel, status: context.profile.status } : null; const fonteValida = context.source.verificationStatus === "verificada" && context.sourceIsEffective; const versaoValida = context.version.reviewStatus === "verificada" && context.versionIsEffective; const perfilValido = !context.profile || context.profile.status === "ativo"; return fonteValida && versaoValida && perfilValido ? { statusDaBase: "verificada" as const, fontes, limitesDeEscopo, perfilSetorial, requerRevisaoHumana: true, podeConcluir: false } : { statusDaBase: "base_insuficiente" as const, fontes, limitesDeEscopo, perfilSetorial, requerRevisaoHumana: true, podeConcluir: false, motivo: "A análise não pode concluir: confirme fonte, versão, vigência, perfil ativo e aplicação ao escopo antes da revisão humana." }; }),
    profileAnalysisGate: protectedProcedure.input(z.object({ profileId: z.number().int().positive() })).query(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); const profile = await getSectorProfileForOrganization(input.profileId, org.organization.id); return { statusDaBase: "perfil_sem_base_documental" as const, fontes: [], limitesDeEscopo: profile.scopeDescription, perfilSetorial: { id: profile.id, nome: profile.name, versao: profile.versionLabel, status: profile.status }, requerRevisaoHumana: true, podeConcluir: false, motivo: "Um perfil setorial é apenas filtro de contexto; selecione um requisito com fonte e versão verificadas para iniciar análise." }; }),
  }),
  sites: router({ create: protectedProcedure.input(z.object({ name: z.string().min(3).max(180), code: z.string().min(2).max(80), city: z.string().max(100).optional(), state: z.string().length(2).optional(), operationalStatus: z.enum(["operacao", "implantacao", "manutencao", "desmobilizado"]).default("operacao"), riskLevel: z.enum(["baixo", "moderado", "alto", "critico"]).default("moderado") })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); return createSite({ ...input, organizationId: org.organization.id }); }) }),
  licenses: router({ create: protectedProcedure.input(z.object({ title: z.string().min(3).max(220), licenseType: z.enum(["LP", "LI", "LO", "outorga", "autorizacao", "outro"]), authority: z.string().max(160).optional(), licenseNumber: z.string().max(120).optional(), siteId: z.number().int().positive().optional(), status: z.enum(["vigente", "em_renovacao", "pendente", "vencida", "suspensa"]).default("pendente"), riskLevel: z.enum(["baixo", "moderado", "alto", "critico"]).default("moderado"), expiryDate: z.number().int().optional() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); if (input.siteId) await assertEntityBelongsToOrganization(org.organization.id, "site", input.siteId); return createLicense({ ...input, organizationId: org.organization.id, expiryDate: input.expiryDate ? new Date(input.expiryDate) : null }); }) }),
  conditions: router({ create: protectedProcedure.input(z.object({ licenseId: z.number().int().positive(), siteId: z.number().int().positive().optional(), code: z.string().max(80).optional(), title: z.string().min(3).max(260), ownerName: z.string().max(160).optional(), dueDate: z.number().int().optional() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); await assertEntityBelongsToOrganization(org.organization.id, "licenca", input.licenseId); if (input.siteId) await assertEntityBelongsToOrganization(org.organization.id, "site", input.siteId); return createCondition({ ...input, organizationId: org.organization.id, dueDate: input.dueDate ? new Date(input.dueDate) : null }); }) }),
  capa: router({
    create: protectedProcedure.input(z.object({ title: z.string().min(3).max(260), siteId: z.number().int().positive().optional(), sourceType: z.enum(["incidente", "inspecao", "auditoria", "condicionante", "outro"]), priority: z.enum(["baixa", "media", "alta", "critica"]), ownerName: z.string().max(160).optional(), dueDate: z.number().int().optional() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); if (input.siteId) await assertEntityBelongsToOrganization(org.organization.id, "site", input.siteId); return createCapaAction({ ...input, organizationId: org.organization.id, dueDate: input.dueDate ? new Date(input.dueDate) : null }); }),
    assignResponsible: protectedProcedure.input(z.object({ capaId: z.number().int().positive(), responsibleUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); await assignCapaResponsible({ ...input, organizationId: org.organization.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "ACTION_RESPONSIBLE_ASSIGNED", resourceType: "capa", resourceId: input.capaId, metadata: JSON.stringify({ responsibleUserId: input.responsibleUserId }) }); return { success: true } as const; }),
  }),
  incidents: router({ create: protectedProcedure.input(z.object({ title: z.string().min(3).max(260), siteId: z.number().int().positive().optional(), incidentType: z.enum(["incidente", "quase_acidente", "condicao_insegura", "ambiental"]), severity: z.enum(["baixa", "moderada", "alta", "critica"]), occurredAt: z.number().int() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); if (input.siteId) await assertEntityBelongsToOrganization(org.organization.id, "site", input.siteId); return createIncident({ ...input, organizationId: org.organization.id, occurredAt: new Date(input.occurredAt) }); }) }),
  esg: router({ createMetric: protectedProcedure.input(z.object({ code: z.string().min(2).max(80), title: z.string().min(3).max(220), category: z.enum(["ambiental", "social", "governanca"]), value: z.number().finite(), target: z.number().finite().optional(), unit: z.string().min(1).max(40), periodLabel: z.string().min(2).max(40), sourceDescription: z.string().max(240).optional(), status: z.enum(["rascunho", "em_revisao", "verificado"]).default("rascunho") })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); return createEsgMetric({ ...input, organizationId: org.organization.id, value: String(input.value), target: input.target === undefined ? null : String(input.target) }); }) }),
  evidences: router({ upload: protectedProcedure.input(z.object({ entityType, entityId: z.number().int().positive().optional(), fileName: z.string().min(1).max(260), mimeType: z.string().min(1).max(120), sizeBytes: z.number().int().positive(), base64: z.string().min(1).max(12_000_000) })).mutation(async ({ ctx, input }) => { validateEvidenceUpload(input); const org = await getRequiredOrganization(ctx.user.id); if (input.entityId && input.entityType === "outro") throw new Error("Registros do tipo 'outro' não podem receber ID de vínculo."); if (input.entityId && input.entityType !== "outro") await assertEntityBelongsToOrganization(org.organization.id, input.entityType as OwnedEntityType, input.entityId); const bytes = Buffer.from(input.base64, "base64"); if (bytes.byteLength !== input.sizeBytes) throw new Error("O tamanho do arquivo não confere com o upload."); const fileName = safeEvidenceName(input.fileName); const stored = await storagePut(`organizations/${org.organization.id}/${input.entityType}/${randomUUID()}-${fileName}`, bytes, input.mimeType); const evidenceId = await createEvidence({ organizationId: org.organization.id, uploadedByUserId: ctx.user.id, entityType: input.entityType, entityId: input.entityId ?? null, fileKey: stored.key, fileUrl: stored.url, fileName, mimeType: input.mimeType, sizeBytes: input.sizeBytes }); await createReviewRequest({ organizationId: org.organization.id, evidenceId, requestedByUserId: ctx.user.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "EVIDENCE_UPLOAD", resourceType: "evidence", resourceId: evidenceId, metadata: JSON.stringify({ entityType: input.entityType, mimeType: input.mimeType, sizeBytes: input.sizeBytes }) }); return evidenceId; }),
    download: protectedProcedure.input(z.object({ evidenceId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); const evidence = await getEvidenceForOrganization(input.evidenceId, org.organization.id); const url = await storageGetSignedUrl(evidence.fileKey); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "EVIDENCE_DOWNLOAD", resourceType: "evidence", resourceId: evidence.id, metadata: JSON.stringify({ mimeType: evidence.mimeType, sizeBytes: evidence.sizeBytes }) }); return { url }; }),
  }),
  reviews: router({
    decide: protectedProcedure.input(z.object({ reviewId: z.number().int().positive(), status: z.enum(["aprovada", "rejeitada"]), note: z.string().trim().max(500).optional() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); if (!canReviewEvidence(org.membership.role)) throw new TRPCError({ code: "FORBIDDEN", message: "Seu perfil não pode revisar evidências." }); await decideReviewRequest({ reviewId: input.reviewId, organizationId: org.organization.id, reviewerUserId: ctx.user.id, status: input.status, note: input.note }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "EVIDENCE_REVIEW_DECIDED", resourceType: "review", resourceId: input.reviewId, metadata: JSON.stringify({ status: input.status }) }); return { success: true } as const; }),
    assignResponsible: protectedProcedure.input(z.object({ reviewId: z.number().int().positive(), reviewerUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); await assignReviewResponsible({ ...input, organizationId: org.organization.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "REVIEW_RESPONSIBLE_ASSIGNED", resourceType: "review", resourceId: input.reviewId, metadata: JSON.stringify({ reviewerUserId: input.reviewerUserId }) }); return { success: true } as const; }),
  }),
  team: router({
    members: protectedProcedure.query(async ({ ctx }) => { const org = await getRequiredOrganization(ctx.user.id); return getTeamOverview(org.organization.id); }),
    invites: protectedProcedure.query(async ({ ctx }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); return getTeamOverview(org.organization.id); }),
    createInvite: protectedProcedure.input(z.object({ email: z.string().trim().email().max(320), role: invitationRole, origin: safeOrigin })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); const email = normalizeInvitationEmail(input.email); if (await getMemberOfOrganizationByEmail(org.organization.id, email)) throw new Error("Este e-mail já é membro da organização."); const token = randomBytes(32).toString("base64url"); const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); const inviteId = await createOrganizationInvite({ organizationId: org.organization.id, email, role: input.role, tokenHash: hashInviteToken(token), createdByUserId: ctx.user.id, expiresAt }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "INVITE_CREATED", resourceType: "organization_invite", resourceId: inviteId, metadata: JSON.stringify({ role: input.role }) }); return { inviteId, invitationUrl: `${input.origin}/convites/${token}`, expiresAt }; }),
    revokeInvite: protectedProcedure.input(z.object({ inviteId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const org = await getRequiredOrganization(ctx.user.id); requireTeamManager(org.membership.role); await revokeOrganizationInvite({ ...input, organizationId: org.organization.id }); await createAuditEvent({ organizationId: org.organization.id, actorUserId: ctx.user.id, action: "INVITE_REVOKED", resourceType: "organization_invite", resourceId: input.inviteId, metadata: null }); return { success: true } as const; }),
  }),
  invitations: router({
    preview: publicProcedure.input(z.object({ token: z.string().min(20).max(200) })).query(async ({ input }) => { const item = await getInviteByHash(hashInviteToken(input.token)); if (!item) return { available: false, organizationName: null, role: null }; return { available: item.invite.status === "pendente" && item.invite.expiresAt.getTime() > Date.now(), organizationName: item.organization.name, role: item.invite.role }; }),
    accept: protectedProcedure.input(z.object({ token: z.string().min(20).max(200) })).mutation(async ({ ctx, input }) => { if (!ctx.user.email) throw new Error("Sua conta precisa ter um e-mail para aceitar o convite."); const organization = await acceptOrganizationInvite({ tokenHash: hashInviteToken(input.token), userId: ctx.user.id, email: normalizeInvitationEmail(ctx.user.email) }); await createAuditEvent({ organizationId: organization.id, actorUserId: ctx.user.id, action: "INVITE_ACCEPTED", resourceType: "organization", resourceId: organization.id, metadata: null }); return organization; }),
  }),
});

export type AppRouter = typeof appRouter;
